### ISSUE TITLE
Support browser FORM submit by passing through name attribute

### ISSUE THREAD

**Issue by downwa** [thecodejack/svelte-file-dropzone#109]
Standard browser FORM submit requires a name attribute for each INPUT element submitted.  Passing through one provided in the tag would make it possible to support standard FORM submit, not just via fetch().

I see that is already fixed in the source code, just needs to be published to npmjs.com

**Comment by Antoine-lb** [comment]
Still no update on this?

**Comment by thecodejack** [comment]
Can you please provide a PR on same?

**Comment by downwa** [comment]
I just installed the package using npm and it now includes the {name} attribute in the INPUT tag.  So I believe this could be closed (unless others are having additional issues with it).

**Comment by ashcdev** [comment]
Yes, I am having issues. When i getAll('photos'), assuming Dropzone has name="photos", the array sends through but if you remove an item from the selected files it does not update the getAll('photos') when sent to the +page.server.js

**Comment by arackaf** [comment]
Name is passed through, and I confirmed the files do indeed post to the form action. If you pull latest on this library, there's now a form path in the demo project which demonstrates this.
