### ISSUE TITLE
Multiple False Doesn't Work

### ISSUE THREAD

**Issue by ghost** [thecodejack/svelte-file-dropzone#140]
I'm using the original code from the documentation and just adding multiple="false":

        <Dropzone multiple="false" on:drop={handleFilesSelect} />
        <ol>
            {#each files.accepted as item}
                <li>{item.name}</li>
            {/each}
        </ol>

but it doesn't seem to work? The list inside ol element still increase even with multiple="false". Here is the result:
![image](https://github.com/thecodejack/svelte-file-dropzone/assets/126843394/ec7e21b6-55d7-494d-8eb7-8f9764a83fdc)

**Comment by wojakmcwagies** [comment]
Wait actually after more testing, the multiple="false" made you unable to SELECT more than 1 file. So the problem might lies in this code instead:

    <ol>
        {#each files.accepted as item}
            <li>{item.name}</li>
        {/each}
    </ol>

Which for some reason doesn't replace the old accepted files when multiple is false.

**Comment by thecodejack** [comment]
Can you please provide PR with the fix?

**Comment by arackaf** [comment]
multiple={false} should work
