### ISSUE TITLE
No Svelte 4 Support...

### ISSUE THREAD

**Issue by rchrdnsh** [thecodejack/svelte-file-dropzone#141]
<img width="654" alt="Screenshot 2023-06-26 at 12 06 36 PM" src="https://github.com/thecodejack/svelte-file-dropzone/assets/7884263/008be582-56a7-45ca-aeb0-3e44baacd92f">

**Comment by bosticka** [comment]
I have the same issue.  As a workaround, I switched to pnpm.  pnmp issues an unmet peer warning but still works and uses svelte 4. pnpm is better than npm anyway...

**Comment by arackaf** [comment]
Sorry - been on vacation - will look to fix soon

**Comment by bosticka** [comment]
Thank you.  Appreciate it!

**Comment by thecodejack** [comment]
@arackaf Let know if you have made some progress on this? Else I can try to take it up?

**Comment by arackaf** [comment]
SO SORRY for the delay. I just pushed a new version with what @bluepuma77 suggested. Can someone test it? I don't have a Svelte project handy that's running on v4

**Comment by arackaf** [comment]
@thecodejack thanks - finally got to it tho :)

**Comment by arackaf** [comment]
Just tested and seems to work
