### ISSUE TITLE
how do you change the text Drag 'n' drop some files here, or click to select files

### ISSUE THREAD

**Issue by craigcosmo** [thecodejack/svelte-file-dropzone#142]
the default text, how do you change it to something else?

`Drag 'n' drop some files here, or click to select files`

**Comment by sho13** [comment]
@craigcosmo the Dropzone component includes a `<slot />` element - https://github.com/thecodejack/svelte-file-dropzone/blob/master/src/lib/components/Dropzone.svelte#L364-L366

in case you haven't heard of the `<slot />` element you can read more [here](https://svelte.dev/docs/special-elements#slot)

TLDR; all you need to do is have Dropzone wrap around whatever you want to replace the text with.

```
<Dropzone>
  <p>Replace default text</p>
</Dropzone
```
