### ISSUE TITLE
with the drop zone inside my form, when I press escape on the mac, it trigger the form close

### ISSUE THREAD

**Issue by craigcosmo** [thecodejack/svelte-file-dropzone#143]
with the drop zone inside my form, when I press escape on the mac, it trigger the form modal close. Why the drop acting like this ?

to reproduce, create a basic modal, put the drop inside, click the drop to choose file, then press `escape`, your modal witll automatically close.

**Comment by arackaf** [comment]
This sounds like behavior of the modal itself. I'm assuming the modal is registering a global keydown event, and closing the modal on escape. I don't think this is a bug with this library. But if I'm misunderstanding, whip up a repro demonstrating and re-open this issue
