### ISSUE TITLE
BUG? [vite] Pre-transform error: Missing "./Dropzone.svelte" specifier in "svelte-file-dropzone" package

### ISSUE THREAD

**Issue by rchrdnsh** [thecodejack/svelte-file-dropzone#156]
Using the latest versions of Svelte, Kit and Vite and svelte-file-dropzone and getting the following error:

```
[vite] Error when evaluating SSR module /src/library/music/finder/Patterns.svelte: failed to import "/src/library/music/midi/MIDIFileUpload.svelte"
|- Error: Missing "./Dropzone.svelte" specifier in "svelte-file-dropzone" package
```

...not sure what needs to change in the package, however.

**Comment by arackaf** [comment]
The import changed, you need to do 

```js
import Dropzone from "svelte-file-dropzone" 
```

without the /Dropzone.svelte on the end

**Comment by rchrdnsh** [comment]
ahhh, much cleaner, and it works again...might want to update the read me 'usage' section :-)

In any case, thank yoooooo :-)
