### ISSUE TITLE
Multiple false text says to select multiple files

### ISSUE THREAD

**Issue by sylc** [thecodejack/svelte-file-dropzone#167]
When setting the option `multiple` to false the text is still advising the user to select multiple files. `Drag 'n' drop some files here, or click to select files`.

I would expect the text be singular in that case eg: `Drag 'n' drop a file here, or click to select 1 file`.

Probably just need an if statement around https://github.com/thecodejack/svelte-file-dropzone/blob/master/src/lib/components/Dropzone.svelte#L338

**Comment by arackaf** [comment]
Fixed in 2.0.9

**Comment by sylc** [comment]
Thanks for the quick fix and the library!
