### ISSUE TITLE
Click event not working in built component

### ISSUE THREAD

**Issue by arackaf** [thecodejack/svelte-file-dropzone#29]
Hey - thanks a TON for building this - it works perfectly. One weird problem though: the built version of this component doesn't work with the click event. In other words, when I click on the Dropzone, the file picking modal does not open. That said, when I link directly to /src/components/Dropzone.svelte it works perfectly. So something is wrong with your build tool. 

That said, is there a reason you're building this at all, instead of just exposing the .svelte file, and allowing consumers to integrate the component into their own build? That's what I've seen other libraries do, and I just figured it was to avoid re-bundling whatever (tiny) utility functions Svelte ships.

**Comment by thecodejack** [comment]
>  the built version of this component doesn't work with the click event.
weird. it's working in my builds. If possible can you please provide reproducer?

 > That said, is there a reason your building this at all, instead of just exposing the .svelte file, and allowing consumers to integrate the component into their own build? That's what I've seen other libraries do
 Will check and provide same.

**Comment by thecodejack** [comment]
@arackaf https://github.com/thecodejack/svelte-file-dropzone/pull/30 is what you were suggesting?

**Comment by arackaf** [comment]
@thecodejack #30 is exactly what I was talking about. I'm relatively new to Svelte - I've seen other libraries expose .svelte files directly, so I assumed it was standard. Not sure why svelte would recommend pre-compiling.

I don't really have a repro - this is my webpack config file, if that helps.

https://github.com/arackaf/booklist/blob/master/svelte/webpack.config.js#L47

Like I said, I'm just hard linking right to the Svelte file, and it works *perfectly* (great work!)

**Comment by thecodejack** [comment]
let me merge this and do a release..that shouldn't be breaking anyways...

**Comment by thecodejack** [comment]
the change of exposing .svelte file is not working in svelte repl
https://svelte.dev/repl/96ba9f8e7ff841f48f71f1f497452e16?version=3.31.0

reverting to js temporarily. Will check further on same.
You can try using `v0.0.13` version till i come with correct format which works in both.



Reg click issue with Webpack config, Will upate once I check on same.

**Comment by arackaf** [comment]
@thecodejack interesting - looks like you're using the "svelte" key in package.json? I had to look that up.

No idea why the Svelte repl doesn't like it... looking now.

**Comment by arackaf** [comment]
@thecodejack oh! I see the problem.

This is what you have in index.svelte

```
import DropZone from "./components/Dropzone.svelte";

export default DropZone;
```

That's not a svelte file! That's a JS file. I think you want, in package.json

"svelte": "src/components/Dropzone.svelte"

**Comment by thecodejack** [comment]
Yep. That's working. Thanks for looking into it. 

Same has been published and available via `0.0.15` version.

Can you please verify if that fixes webpack issue you were facing?

**Comment by arackaf** [comment]
@thecodejack will do tomorrow - thanks a ton!

**Comment by arackaf** [comment]
Works perfectly

**Comment by arackaf** [comment]
fyi the package.json I see in github shows 0.0.14 - looks like you might have some pending changes you didn't commit?

**Comment by thecodejack** [comment]
Thanks for heads up...fixed it..
