### ISSUE TITLE
"es is not a function" when you select or drag a file

### ISSUE THREAD

**Issue by hasimsait** [thecodejack/svelte-file-dropzone#3]
Uncaught (in promise) TypeError: es is not a function
    fileAccepted index.js:44
    onDropCb Dropzone.svelte:194
    onDropCb Dropzone.svelte:193
    promise callback*onDropCb Dropzone.svelte:185
index.js:44:46
 in both Chrome and Firefox.

to reproduce it:
https://gist.github.com/hasimsait/8a666cc2098f8b0c79106e274fe69030 (insert code didn't work unfortunately)

I want to replace the 
`<input type="file" class="custom-file-input needs-gap" name="customFile" id="customFile">
    <label class="custom-file-label" for="customFile">Choose file</label>`
with a dropzone but it gives me this error.

**Comment by thecodejack** [comment]
@hasimsait sorry for late reply here. Tried reproducing the issue but working for me. Can you please share repl link with the issue (https://svelte.dev/repl)?

**Comment by AbePralle** [comment]
I just encountered this today as well (haven't used SFDZ before). I also get "es is not a function" on my local project. On REPL I get this warning on load (using the example code from this repo):

"<Dropzone> was created without expected prop 'accept'"

and this error on dragging in a JPEG file:

Error:
message: "Uncaught (in promise): accepts is not a function"
stack: TypeError: accepts is not a function
at fileAccepted (eval at handle_message (about:srcdoc:13:8), <anonymous>:815:51)
at eval (eval at handle_message (about:srcdoc:13:8), <anonymous>:1251:42)
at Array.forEach (<anonymous>)
at eval (eval at handle_message (about:srcdoc:13:8), <anonymous>:1250:15)

Here's the REPL:
https://svelte.dev/repl/255c36493ea442f3988f889ca9ab875b?version=3.29.4

**Comment by thecodejack** [comment]
thanks for reproducing.  Weird that this is not happening with rollup setup I have.

Looking into that.

**Comment by thecodejack** [comment]
fixed with PR#1

**Comment by thecodejack** [comment]
`svelte-file-dropzone@0.0.12` has the fix. Tested with same repl link
