### ISSUE TITLE
Is there SSR support that I am missing somewhere? 

### ISSUE THREAD

**Issue by cgibsonmm** [thecodejack/svelte-file-dropzone#47]
With sapper I am running into 

`<Dropzone> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

Any way to solve this out of the box?

**Comment by diegofhe** [comment]
I had the same issue. A quick workaround is to put the component inside and if and setting a ready variable onMount.

Eg

```
<script>
    import Dropzone from 'svelte-file-dropzone';
    import {onMount} from 'svelte';
    let ready = false
  
    onMount(async () => {
        ready = true
    });
</script>

{#if ready}
    <Dropzone/>
{/if}
```

We can do this while waiting for the package to be updated

**Comment by thecodejack** [comment]
Sorry for late reply here. I will look into the issue in couple of days. Would welcome if we can get a PR for same.

**Comment by mylastore** [comment]
Confirm @diegofhe  work around worked for me. Thanks ;)

**Comment by thecodejack** [comment]
finding hard to find time for the fix. I would be open for PRs on this

**Comment by thecodejack** [comment]
unable to find time for this. Open for PRs.
