### ISSUE TITLE
is multiple=false working?

### ISSUE THREAD

**Issue by llPekoll** [thecodejack/svelte-file-dropzone#79]
multiple parameter doesn't seem to work :/
you can add files and the list below is still increasing.

**Comment by thecodejack** [comment]
should be a simple fix. Can any of you provide a PR with the fix?

**Comment by jonnitto** [comment]
Hi there! Any progress on this?

**Comment by thecodejack** [comment]
working for me. Please share reproducible. 

feel free to reopen.
