### ISSUE TITLE
Bundling issue

### ISSUE THREAD

**Issue by Seon82** [thecodejack/svelte-file-dropzone#88]
Using version `1.0.0-dev.1`.
I'm trying to run the README example code with the official Svelte template but nothing renders onscreen, and the following errors are logged during bundling:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
svelte-file-dropzone (imported by src/App.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
svelte-file-dropzone (guessing 'Dropzone')
```
Copying the README's example code into the svelte REPL seems to cause a similar issue. The error isn't present in `0.0.15`.

**Comment by thecodejack** [comment]
1.0.0-dev.1 is not stable. Please use 0.0.15 only
