### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by WardPearce** [thecodejack/svelte-file-dropzone#91]
When trying to use this lib with vite, following errors occur
```
[vite] Internal server error: Failed to resolve import "$app/env" from "node_modules/svelte-file-dropzone/src/components/Dropzone.svelte". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/ward/Documents/Git/paaster/paaster-frontend/node_modules/svelte-file-dropzone/src/components/Dropzone.svelte
  26 |  } from "svelte/internal";
  27 |  
  28 |  import { browser } from "$app/env";
     |                           ^
  29 |  import { fromEvent } from "file-selector";
```

### Discussion with Vite land team member
![chat](https://i.imgur.com/HW5ihLX.png)

**Comment by thecodejack** [comment]
Ok looks like dev version of v1 is causing trouble. Similar to #95 . Will rethink about that approach and probably overwrite same in newer version.

**Comment by Tal500** [comment]
> Ok looks like dev version of v1 is causing trouble. Similar to #95 . Will rethink about that approach and probably overwrite same in newer version.

The same problem happen to me, I had to downgrade this package version. 

I suggest to delete/rename these v1 versions from the NPM registry, I think you have the option to delete them.

**Comment by thecodejack** [comment]
I can do but devs using SvelteKit have trouble to use during SSR. So back then gave them this version which started breaking non Sveltkit users. I have to see if Svelkit fixed `onDestroy`. Till then, probably I have a new version which fixes this. But Sveltkit users forced to have fixed version instead.

**Comment by Tal500** [comment]
> I can do but devs using SvelteKit have trouble to use during SSR. So back then gave them this version which started breaking non Sveltkit users. I have to see if Svelkit fixed `onDestroy`. Till then, probably I have a new version which fixes this. But Sveltkit users forced to have fixed version instead.

The problem was that you used the browser "window" API that is available only on client side, so it throws an error when using it on the server side(during SSR).

The last PR you merged (#105 ) solved this problem easily, so now all Svelte users (including SvelteKit) can safely use the new version containing my PR.

**Comment by thecodejack** [comment]
ok. awesome. I haven't tested that usecase.

**Comment by thecodejack** [comment]
have release v1 which should fix the issue. Please reopen if found otherwise.
