### ISSUE TITLE
Unable to validate input without exposing more input attributes / events

### ISSUE THREAD

**Issue by zwergius** [thecodejack/svelte-file-dropzone#93]
Hi, 

First of all, thanks for porting this to Svelte!

Here is a small feature request.

I regularly use the native html 5 validation api to validate my forms, but I cannot accomplish this in a satisfying way using this component. 

On a regular input I use the following attributes/events
<img width="619" alt="image" src="https://user-images.githubusercontent.com/2060308/159667494-e946e423-6cdf-4e6b-a216-c7f06bbe6edd.png">

I believe you should open up to add any attribute to the input. 

Hope to see this implemented.

Thanks in advance

**Comment by thecodejack** [comment]
aah ok..makes sense...I will look into that sometime..PRs are welcome as well.
